spring.application.name=SIGMA


spring.profiles.active=prod

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=60000


server.port=${PORT:8080}
